plugins { id 'com.android.application'; id 'com.google.gms.google-services' }
android {
    namespace 'com.anshify.myapp'
    compileSdk 34
    defaultConfig {
        applicationId 'com.anshify.myapp'
        minSdk 21
        targetSdk 34
        versionCode 2
        versionName '1.0.2'
    }
    androidResources {
        noCompress 'html'
    }
    def ks = file('anshify.p12')
    if (ks.exists()) {
        signingConfigs { anshify { storeFile ks; storeType 'pkcs12'; storePassword 'anshify123'; keyAlias 'anshify'; keyPassword 'anshify123' } }
        buildTypes {
            debug { signingConfig signingConfigs.anshify }
            release { signingConfig signingConfigs.anshify }
        }
    }
    if (!ks.exists()) {
        buildTypes { release { signingConfig signingConfigs.debug } }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies { implementation platform('com.google.firebase:firebase-bom:33.7.0'); implementation 'com.google.firebase:firebase-messaging' }
